packages:
  - 'apps/**'
  - 'client/web'
  - 'client/shared'
  - 'client/web/plugins/**'
  - 'client/packages/**'
  - 'server'
  - 'server/admin'
  - 'server/packages/**'
  - 'server/plugins/**'
  - 'cli'
  - 'website'
